version: '3.7'

services:
  <container_name>:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: <container_name>
    restart: always
    volumes:
      - ./src:/app
      - /app/vendor
    networks:
      - nginx_proxy-network
    
networks:
  nginx_proxy-network:
    external: true