version: '3.7'

services:
  nmsapps:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: websitelocal
    restart: always
    volumes:
      - ./src:/app
      - /app/vendor
    networks:
      - nginx_proxy-network
    
networks:
  nginx_proxy-network:
    external: true