version: '3.7'

services:
  redis62:
    image: redis:6.2
    container_name: redis62
    restart: always
    ports:
      - 6379:6379
    networks:
      - nginx_proxy-network


networks:
  nginx_proxy-network:
    external: true
