version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
