version: '3.7'

services:
  mariadb104:
    image: mariadb:10.4
    container_name: mariadb104
    ports:
      - 4000:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=devpassword
      - MYSQL_USER=dev_user
    networks:
      - nginx_proxy-network


networks:
  nginx_proxy-network:
    external: true
